<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllBackofficeCoursesSearcherService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Backoffice\Courses\Application\SearchAll\AllBackofficeCoursesSearcher' shared autowired service.
     *
     * @return \CodelyTv\Backoffice\Courses\Application\SearchAll\AllBackofficeCoursesSearcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Backoffice/Courses/Application/SearchAll/AllBackofficeCoursesSearcher.php';

        return $container->privates['CodelyTv\\Backoffice\\Courses\\Application\\SearchAll\\AllBackofficeCoursesSearcher'] = new \CodelyTv\Backoffice\Courses\Application\SearchAll\AllBackofficeCoursesSearcher(($container->privates['CodelyTv\\Backoffice\\Courses\\Infrastructure\\Persistence\\ElasticsearchBackofficeCourseRepository'] ?? $container->load('getElasticsearchBackofficeCourseRepositoryService')));
    }
}
