<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationFeatureContextService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'CodelyTv\Tests\Shared\Infrastructure\Behat\ApplicationFeatureContext' shared autowired service.
     *
     * @return \CodelyTv\Tests\Shared\Infrastructure\Behat\ApplicationFeatureContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 7).'/tests/Shared/Infrastructure/Behat/ApplicationFeatureContext.php';

        return $container->services['CodelyTv\\Tests\\Shared\\Infrastructure\\Behat\\ApplicationFeatureContext'] = new \CodelyTv\Tests\Shared\Infrastructure\Behat\ApplicationFeatureContext(($container->privates['CodelyTv\\Shared\\Infrastructure\\Doctrine\\DatabaseConnections'] ?? $container->load('getDatabaseConnectionsService')), ($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\InMemory\\InMemorySymfonyEventBus'] ?? $container->load('getInMemorySymfonyEventBusService')), ($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\DomainEventJsonDeserializer'] ?? $container->load('getDomainEventJsonDeserializerService')));
    }
}
