<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthenticateUserCommandHandlerService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Backoffice\Auth\Application\Authenticate\AuthenticateUserCommandHandler' shared autowired service.
     *
     * @return \CodelyTv\Backoffice\Auth\Application\Authenticate\AuthenticateUserCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Command/CommandHandler.php';
        include_once \dirname(__DIR__, 7).'/src/Backoffice/Auth/Application/Authenticate/AuthenticateUserCommandHandler.php';

        return $container->privates['CodelyTv\\Backoffice\\Auth\\Application\\Authenticate\\AuthenticateUserCommandHandler'] = new \CodelyTv\Backoffice\Auth\Application\Authenticate\AuthenticateUserCommandHandler(($container->privates['CodelyTv\\Backoffice\\Auth\\Application\\Authenticate\\UserAuthenticator'] ?? $container->load('getUserAuthenticatorService')));
    }
}
