<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityManagerService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'Doctrine\ORM\EntityManager' shared service.
     *
     * @return \Doctrine\ORM\EntityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/vendor/doctrine/persistence/src/Persistence/ObjectManager.php';
        include_once \dirname(__DIR__, 7).'/vendor/doctrine/orm/src/EntityManagerInterface.php';
        include_once \dirname(__DIR__, 7).'/vendor/doctrine/orm/src/EntityManager.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Shared/Infrastructure/Doctrine/MoocEntityManagerFactory.php';

        return $container->services['Doctrine\\ORM\\EntityManager'] = \CodelyTv\Mooc\Shared\Infrastructure\Doctrine\MoocEntityManagerFactory::create(['driver' => $container->getEnv('MOOC_DATABASE_DRIVER'), 'host' => $container->getEnv('MOOC_DATABASE_HOST'), 'port' => $container->getEnv('MOOC_DATABASE_PORT'), 'dbname' => $container->getEnv('MOOC_DATABASE_NAME'), 'user' => $container->getEnv('MOOC_DATABASE_USER'), 'password' => $container->getEnv('MOOC_DATABASE_PASSWORD')], $container->getEnv('APP_ENV'));
    }
}
