<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElasticsearchClientFactoryService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Elasticsearch\ElasticsearchClientFactory' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Elasticsearch\ElasticsearchClientFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Elasticsearch/ElasticsearchClientFactory.php';

        return $container->privates['CodelyTv\\Shared\\Infrastructure\\Elasticsearch\\ElasticsearchClientFactory'] = new \CodelyTv\Shared\Infrastructure\Elasticsearch\ElasticsearchClientFactory();
    }
}
