<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElasticsearchClientService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'CodelyTv\Shared\Infrastructure\Elasticsearch\ElasticsearchClient' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Elasticsearch\ElasticsearchClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Elasticsearch/ElasticsearchClient.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Elasticsearch/ElasticsearchClientFactory.php';

        return $container->services['CodelyTv\\Shared\\Infrastructure\\Elasticsearch\\ElasticsearchClient'] = ($container->privates['CodelyTv\\Shared\\Infrastructure\\Elasticsearch\\ElasticsearchClientFactory'] ??= new \CodelyTv\Shared\Infrastructure\Elasticsearch\ElasticsearchClientFactory())->__invoke($container->getEnv('BACKOFFICE_ELASTICSEARCH_HOST'), $container->getEnv('BACKOFFICE_ELASTICSEARCH_INDEX_PREFIX'), (\dirname(__DIR__, 4).'/../../../etc/databases/backoffice'), $container->getEnv('APP_ENV'));
    }
}
