<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElasticsearchBackofficeCourseRepositoryService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Backoffice\Courses\Infrastructure\Persistence\ElasticsearchBackofficeCourseRepository' shared autowired service.
     *
     * @return \CodelyTv\Backoffice\Courses\Infrastructure\Persistence\ElasticsearchBackofficeCourseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Persistence/Elasticsearch/ElasticsearchRepository.php';
        include_once \dirname(__DIR__, 7).'/src/Backoffice/Courses/Domain/BackofficeCourseRepository.php';
        include_once \dirname(__DIR__, 7).'/src/Backoffice/Courses/Infrastructure/Persistence/ElasticsearchBackofficeCourseRepository.php';

        return $container->privates['CodelyTv\\Backoffice\\Courses\\Infrastructure\\Persistence\\ElasticsearchBackofficeCourseRepository'] = new \CodelyTv\Backoffice\Courses\Infrastructure\Persistence\ElasticsearchBackofficeCourseRepository(($container->services['CodelyTv\\Shared\\Infrastructure\\Elasticsearch\\ElasticsearchClient'] ?? $container->load('getElasticsearchClientService')));
    }
}
