<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthCheckGetControllerService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'CodelyTv\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController' shared autowired service.
     *
     * @return \CodelyTv\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HealthCheck/HealthCheckGetController.php';

        return $container->services['CodelyTv\\Apps\\Backoffice\\Backend\\Controller\\HealthCheck\\HealthCheckGetController'] = new \CodelyTv\Apps\Backoffice\Backend\Controller\HealthCheck\HealthCheckGetController();
    }
}
