<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInMemorySymfonyQueryBusService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Query/QueryBus.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Bus/Query/InMemorySymfonyQueryBus.php';

        return $container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Query\\InMemorySymfonyQueryBus'] = new \CodelyTv\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['CodelyTv\\Backoffice\\Courses\\Application\\SearchAll\\SearchAllBackofficeCoursesQueryHandler'] ?? $container->load('getSearchAllBackofficeCoursesQueryHandlerService'));
            yield 1 => ($container->privates['CodelyTv\\Backoffice\\Courses\\Application\\SearchByCriteria\\SearchBackofficeCoursesByCriteriaQueryHandler'] ?? $container->load('getSearchBackofficeCoursesByCriteriaQueryHandlerService'));
        }, 2));
    }
}
