<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInMemorySymfonyEventBusService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\InMemory\\InMemorySymfonyEventBus'] = $container->createProxy('InMemorySymfonyEventBusGhostD920c50', static fn () => \InMemorySymfonyEventBusGhostD920c50::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Event/EventBus.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Bus/Event/InMemory/InMemorySymfonyEventBus.php';

        return ($lazyLoad->__construct(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['CodelyTv\\Backoffice\\Courses\\Application\\Create\\CreateBackofficeCourseOnCourseCreated'] ?? $container->load('getCreateBackofficeCourseOnCourseCreatedService'));
        }, 1)) && false ?: $lazyLoad);
    }
}
