<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetricsControllerService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'CodelyTv\Apps\Backoffice\Backend\Controller\Metrics\MetricsController' shared autowired service.
     *
     * @return \CodelyTv\Apps\Backoffice\Backend\Controller\Metrics\MetricsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Metrics/MetricsController.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Monitoring/PrometheusMonitor.php';

        return $container->services['CodelyTv\\Apps\\Backoffice\\Backend\\Controller\\Metrics\\MetricsController'] = new \CodelyTv\Apps\Backoffice\Backend\Controller\Metrics\MetricsController(($container->privates['CodelyTv\\Shared\\Infrastructure\\Monitoring\\PrometheusMonitor'] ??= new \CodelyTv\Shared\Infrastructure\Monitoring\PrometheusMonitor()));
    }
}
