<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchAllBackofficeCoursesQueryHandlerService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Backoffice\Courses\Application\SearchAll\SearchAllBackofficeCoursesQueryHandler' shared autowired service.
     *
     * @return \CodelyTv\Backoffice\Courses\Application\SearchAll\SearchAllBackofficeCoursesQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Query/QueryHandler.php';
        include_once \dirname(__DIR__, 7).'/src/Backoffice/Courses/Application/SearchAll/SearchAllBackofficeCoursesQueryHandler.php';

        return $container->privates['CodelyTv\\Backoffice\\Courses\\Application\\SearchAll\\SearchAllBackofficeCoursesQueryHandler'] = new \CodelyTv\Backoffice\Courses\Application\SearchAll\SearchAllBackofficeCoursesQueryHandler(($container->privates['CodelyTv\\Backoffice\\Courses\\Application\\SearchAll\\AllBackofficeCoursesSearcher'] ?? $container->load('getAllBackofficeCoursesSearcherService')));
    }
}
