<?php

namespace ContainerYDryPxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchBackofficeCoursesByCriteriaQueryHandlerService extends CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Backoffice\Courses\Application\SearchByCriteria\SearchBackofficeCoursesByCriteriaQueryHandler' shared autowired service.
     *
     * @return \CodelyTv\Backoffice\Courses\Application\SearchByCriteria\SearchBackofficeCoursesByCriteriaQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Query/QueryHandler.php';
        include_once \dirname(__DIR__, 7).'/src/Backoffice/Courses/Application/SearchByCriteria/SearchBackofficeCoursesByCriteriaQueryHandler.php';

        return $container->privates['CodelyTv\\Backoffice\\Courses\\Application\\SearchByCriteria\\SearchBackofficeCoursesByCriteriaQueryHandler'] = new \CodelyTv\Backoffice\Courses\Application\SearchByCriteria\SearchBackofficeCoursesByCriteriaQueryHandler(($container->privates['CodelyTv\\Backoffice\\Courses\\Application\\SearchByCriteria\\BackofficeCoursesByCriteriaSearcher'] ?? $container->load('getBackofficeCoursesByCriteriaSearcherService')));
    }
}
