<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYDryPxj\CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYDryPxj/CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYDryPxj.legacy');

    return;
}

if (!\class_exists(CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYDryPxj\CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer::class, CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer::class, false);
}

return new \ContainerYDryPxj\CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainer([
    'container.build_hash' => 'YDryPxj',
    'container.build_id' => '6cf64228',
    'container.build_time' => 1728494565,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYDryPxj');
