<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerESpBA67\CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerESpBA67/CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerESpBA67.legacy');

    return;
}

if (!\class_exists(CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerESpBA67\CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer::class, CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer::class, false);
}

return new \ContainerESpBA67\CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer([
    'container.build_hash' => 'ESpBA67',
    'container.build_id' => '233ff571',
    'container.build_time' => 1728494551,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerESpBA67');
