<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiExceptionsHttpStatusCodeMappingService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Symfony\ApiExceptionsHttpStatusCodeMapping' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Symfony\ApiExceptionsHttpStatusCodeMapping
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Symfony/ApiExceptionsHttpStatusCodeMapping.php';

        return $container->privates['CodelyTv\\Shared\\Infrastructure\\Symfony\\ApiExceptionsHttpStatusCodeMapping'] = new \CodelyTv\Shared\Infrastructure\Symfony\ApiExceptionsHttpStatusCodeMapping();
    }
}
