<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateVideoStepCommandHandlerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\Steps\Application\Create\CreateVideoStepCommandHandler' shared autowired service.
     *
     * @return \CodelyTv\Mooc\Steps\Application\Create\CreateVideoStepCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Command/CommandHandler.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Steps/Application/Create/CreateVideoStepCommandHandler.php';

        return $container->privates['CodelyTv\\Mooc\\Steps\\Application\\Create\\CreateVideoStepCommandHandler'] = new \CodelyTv\Mooc\Steps\Application\Create\CreateVideoStepCommandHandler(($container->privates['CodelyTv\\Mooc\\Steps\\Application\\Create\\VideoStepCreator'] ?? $container->load('getVideoStepCreatorService')));
    }
}
