<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursesPutControllerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'CodelyTv\Apps\Mooc\Backend\Controller\Courses\CoursesPutController' shared autowired service.
     *
     * @return \CodelyTv\Apps\Mooc\Backend\Controller\Courses\CoursesPutController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Symfony/ApiController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Courses/CoursesPutController.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Symfony/ApiExceptionsHttpStatusCodeMapping.php';

        return $container->services['CodelyTv\\Apps\\Mooc\\Backend\\Controller\\Courses\\CoursesPutController'] = new \CodelyTv\Apps\Mooc\Backend\Controller\Courses\CoursesPutController(($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Query\\InMemorySymfonyQueryBus'] ?? $container->load('getInMemorySymfonyQueryBusService')), ($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Command\\InMemorySymfonyCommandBus'] ?? $container->load('getInMemorySymfonyCommandBusService')), ($container->privates['CodelyTv\\Shared\\Infrastructure\\Symfony\\ApiExceptionsHttpStatusCodeMapping'] ??= new \CodelyTv\Shared\Infrastructure\Symfony\ApiExceptionsHttpStatusCodeMapping()));
    }
}
