<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursesCounterIncrementerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\CoursesCounter\Application\Increment\CoursesCounterIncrementer' shared autowired service.
     *
     * @return \CodelyTv\Mooc\CoursesCounter\Application\Increment\CoursesCounterIncrementer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Mooc/CoursesCounter/Application/Increment/CoursesCounterIncrementer.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/UuidGenerator.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/RamseyUuidGenerator.php';

        return $container->privates['CodelyTv\\Mooc\\CoursesCounter\\Application\\Increment\\CoursesCounterIncrementer'] = new \CodelyTv\Mooc\CoursesCounter\Application\Increment\CoursesCounterIncrementer(($container->privates['CodelyTv\\Mooc\\CoursesCounter\\Infrastructure\\Persistence\\DoctrineCoursesCounterRepository'] ?? $container->load('getDoctrineCoursesCounterRepositoryService')), ($container->privates['CodelyTv\\Shared\\Infrastructure\\RamseyUuidGenerator'] ??= new \CodelyTv\Shared\Infrastructure\RamseyUuidGenerator()), ($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\WithMonitoring\\WithPrometheusMonitoringEventBus'] ?? $container->load('getWithPrometheusMonitoringEventBusService')));
    }
}
