<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_ValidatorExpressionLanguageService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'cache.validator_expression_language' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\AdapterInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/vendor/psr/cache/src/CacheItemPoolInterface.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/cache/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/cache-contracts/CacheInterface.php';
        include_once \dirname(__DIR__, 7).'/vendor/psr/log/src/LoggerAwareInterface.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/cache/ResettableInterface.php';
        include_once \dirname(__DIR__, 7).'/vendor/psr/log/src/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/cache/Traits/AbstractAdapterTrait.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/cache-contracts/CacheTrait.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/cache/Traits/ContractsTrait.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/cache/Adapter/AbstractAdapter.php';

        return $container->services['cache.validator_expression_language'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('QQKC8kEH5a', 0, $container->getParameter('container.build_id'), ($container->targetDir.''.'/pools/system'), ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
