<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourseCreatorService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\Courses\Application\Create\CourseCreator' shared autowired service.
     *
     * @return \CodelyTv\Mooc\Courses\Application\Create\CourseCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Mooc/Courses/Application/Create/CourseCreator.php';

        return $container->privates['CodelyTv\\Mooc\\Courses\\Application\\Create\\CourseCreator'] = new \CodelyTv\Mooc\Courses\Application\Create\CourseCreator(($container->privates['CodelyTv\\Mooc\\Courses\\Infrastructure\\Persistence\\DoctrineCourseRepository'] ?? $container->load('getDoctrineCourseRepositoryService')), ($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\WithMonitoring\\WithPrometheusMonitoringEventBus'] ?? $container->load('getWithPrometheusMonitoringEventBusService')));
    }
}
