<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateCourseCommandHandlerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\Courses\Application\Create\CreateCourseCommandHandler' shared autowired service.
     *
     * @return \CodelyTv\Mooc\Courses\Application\Create\CreateCourseCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Command/CommandHandler.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Courses/Application/Create/CreateCourseCommandHandler.php';

        return $container->privates['CodelyTv\\Mooc\\Courses\\Application\\Create\\CreateCourseCommandHandler'] = new \CodelyTv\Mooc\Courses\Application\Create\CreateCourseCommandHandler(($container->privates['CodelyTv\\Mooc\\Courses\\Application\\Create\\CourseCreator'] ?? $container->load('getCourseCreatorService')));
    }
}
