<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursesCounterFinderService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\CoursesCounter\Application\Find\CoursesCounterFinder' shared autowired service.
     *
     * @return \CodelyTv\Mooc\CoursesCounter\Application\Find\CoursesCounterFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Mooc/CoursesCounter/Application/Find/CoursesCounterFinder.php';

        return $container->privates['CodelyTv\\Mooc\\CoursesCounter\\Application\\Find\\CoursesCounterFinder'] = new \CodelyTv\Mooc\CoursesCounter\Application\Find\CoursesCounterFinder(($container->privates['CodelyTv\\Mooc\\CoursesCounter\\Infrastructure\\Persistence\\DoctrineCoursesCounterRepository'] ?? $container->load('getDoctrineCoursesCounterRepositoryService')));
    }
}
