<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateVideoCommandHandlerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\Videos\Application\Create\CreateVideoCommandHandler' shared autowired service.
     *
     * @return \CodelyTv\Mooc\Videos\Application\Create\CreateVideoCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Command/CommandHandler.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Videos/Application/Create/CreateVideoCommandHandler.php';

        return $container->privates['CodelyTv\\Mooc\\Videos\\Application\\Create\\CreateVideoCommandHandler'] = new \CodelyTv\Mooc\Videos\Application\Create\CreateVideoCommandHandler(($container->privates['CodelyTv\\Mooc\\Videos\\Application\\Create\\VideoCreator'] ?? $container->load('getVideoCreatorService')));
    }
}
