<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigureRabbitMqCommand_LazyService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private '.CodelyTv\Apps\Mooc\Backend\Command\DomainEvents\RabbitMq\ConfigureRabbitMqCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.CodelyTv\\Apps\\Mooc\\Backend\\Command\\DomainEvents\\RabbitMq\\ConfigureRabbitMqCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('codely:domain-events:rabbitmq:configure', [], 'Configure the RabbitMQ to allow publish & consume domain events', false, #[\Closure(name: 'CodelyTv\\Apps\\Mooc\\Backend\\Command\\DomainEvents\\RabbitMq\\ConfigureRabbitMqCommand')] fn (): \CodelyTv\Apps\Mooc\Backend\Command\DomainEvents\RabbitMq\ConfigureRabbitMqCommand => ($container->privates['CodelyTv\\Apps\\Mooc\\Backend\\Command\\DomainEvents\\RabbitMq\\ConfigureRabbitMqCommand'] ?? $container->load('getConfigureRabbitMqCommandService')));
    }
}
