<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainEventSubscriberLocatorService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Bus/Event/DomainEventSubscriberLocator.php';

        return $container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\DomainEventSubscriberLocator'] = new \CodelyTv\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['CodelyTv\\Mooc\\CoursesCounter\\Application\\Increment\\IncrementCoursesCounterOnCourseCreated'] ?? $container->load('getIncrementCoursesCounterOnCourseCreatedService'));
        }, 1));
    }
}
