<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineCourseRepositoryService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\Courses\Infrastructure\Persistence\DoctrineCourseRepository' shared autowired service.
     *
     * @return \CodelyTv\Mooc\Courses\Infrastructure\Persistence\DoctrineCourseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Persistence/Doctrine/DoctrineRepository.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Courses/Domain/CourseRepository.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Courses/Infrastructure/Persistence/DoctrineCourseRepository.php';

        return $container->privates['CodelyTv\\Mooc\\Courses\\Infrastructure\\Persistence\\DoctrineCourseRepository'] = new \CodelyTv\Mooc\Courses\Infrastructure\Persistence\DoctrineCourseRepository(($container->services['Doctrine\\ORM\\EntityManager'] ?? $container->load('getEntityManagerService')));
    }
}
