<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindCoursesCounterQueryHandlerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\CoursesCounter\Application\Find\FindCoursesCounterQueryHandler' shared autowired service.
     *
     * @return \CodelyTv\Mooc\CoursesCounter\Application\Find\FindCoursesCounterQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Query/QueryHandler.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/CoursesCounter/Application/Find/FindCoursesCounterQueryHandler.php';

        return $container->privates['CodelyTv\\Mooc\\CoursesCounter\\Application\\Find\\FindCoursesCounterQueryHandler'] = new \CodelyTv\Mooc\CoursesCounter\Application\Find\FindCoursesCounterQueryHandler(($container->privates['CodelyTv\\Mooc\\CoursesCounter\\Application\\Find\\CoursesCounterFinder'] ?? $container->load('getCoursesCounterFinderService')));
    }
}
