<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthCheckGetControllerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'CodelyTv\Apps\Mooc\Backend\Controller\HealthCheck\HealthCheckGetController' shared autowired service.
     *
     * @return \CodelyTv\Apps\Mooc\Backend\Controller\HealthCheck\HealthCheckGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HealthCheck/HealthCheckGetController.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/RandomNumberGenerator.php';
        include_once \dirname(__DIR__, 7).'/tests/Shared/Infrastructure/ConstantRandomNumberGenerator.php';

        return $container->services['CodelyTv\\Apps\\Mooc\\Backend\\Controller\\HealthCheck\\HealthCheckGetController'] = new \CodelyTv\Apps\Mooc\Backend\Controller\HealthCheck\HealthCheckGetController(($container->privates['CodelyTv\\Tests\\Shared\\Infrastructure\\ConstantRandomNumberGenerator'] ??= new \CodelyTv\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator()));
    }
}
