<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInMemorySymfonyCommandBusService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Command/CommandBus.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Bus/Command/InMemorySymfonyCommandBus.php';

        return $container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Command\\InMemorySymfonyCommandBus'] = new \CodelyTv\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['CodelyTv\\Mooc\\Courses\\Application\\Create\\CreateCourseCommandHandler'] ?? $container->load('getCreateCourseCommandHandlerService'));
            yield 1 => ($container->privates['CodelyTv\\Mooc\\Steps\\Application\\Create\\CreateVideoStepCommandHandler'] ?? $container->load('getCreateVideoStepCommandHandlerService'));
            yield 2 => ($container->privates['CodelyTv\\Mooc\\Videos\\Application\\Create\\CreateVideoCommandHandler'] ?? $container->load('getCreateVideoCommandHandlerService'));
        }, 3));
    }
}
