<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Default_Middleware_HandleMessageService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.bus.default.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 7).'/vendor/psr/log/src/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';

        $a = ($container->privates['messenger.bus.default.messenger.handlers_locator'] ?? $container->load('getMessenger_Bus_Default_Messenger_HandlersLocatorService'));

        if (isset($container->privates['messenger.bus.default.middleware.handle_message'])) {
            return $container->privates['messenger.bus.default.middleware.handle_message'];
        }

        $container->privates['messenger.bus.default.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware($a, false);

        $instance->setLogger(($container->privates['logger'] ?? self::getLoggerService($container)));

        return $instance;
    }
}
