<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMySqlStepRepositoryService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\Steps\Infrastructure\Persistence\MySqlStepRepository' shared autowired service.
     *
     * @return \CodelyTv\Mooc\Steps\Infrastructure\Persistence\MySqlStepRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Persistence/Doctrine/DoctrineRepository.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Steps/Domain/StepRepository.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Steps/Infrastructure/Persistence/MySqlStepRepository.php';

        return $container->privates['CodelyTv\\Mooc\\Steps\\Infrastructure\\Persistence\\MySqlStepRepository'] = new \CodelyTv\Mooc\Steps\Infrastructure\Persistence\MySqlStepRepository(($container->services['Doctrine\\ORM\\EntityManager'] ?? $container->load('getEntityManagerService')));
    }
}
