<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublishDomainEventsFromMutationsCommand_LazyService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private '.CodelyTv\Apps\Mooc\Backend\Command\DomainEvents\PublishDomainEventsFromMutationsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 7).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.CodelyTv\\Apps\\Mooc\\Backend\\Command\\DomainEvents\\PublishDomainEventsFromMutationsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('codely:domain-events:generate-from-mutations', [], 'Publish domain events from mutations', false, #[\Closure(name: 'CodelyTv\\Apps\\Mooc\\Backend\\Command\\DomainEvents\\PublishDomainEventsFromMutationsCommand')] fn (): \CodelyTv\Apps\Mooc\Backend\Command\DomainEvents\PublishDomainEventsFromMutationsCommand => ($container->privates['CodelyTv\\Apps\\Mooc\\Backend\\Command\\DomainEvents\\PublishDomainEventsFromMutationsCommand'] ?? $container->load('getPublishDomainEventsFromMutationsCommandService')));
    }
}
