<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRabbitMqConfigurerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConfigurer' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConfigurer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Bus/Event/RabbitMq/RabbitMqConfigurer.php';

        return $container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\RabbitMq\\RabbitMqConfigurer'] = new \CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConfigurer(($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\RabbitMq\\RabbitMqConnection'] ?? $container->load('getRabbitMqConnectionService')));
    }
}
