<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRabbitMqDomainEventsConsumerService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqDomainEventsConsumer' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqDomainEventsConsumer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Bus/Event/RabbitMq/RabbitMqDomainEventsConsumer.php';

        return $container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\RabbitMq\\RabbitMqDomainEventsConsumer'] = new \CodelyTv\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqDomainEventsConsumer(($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\RabbitMq\\RabbitMqConnection'] ?? $container->load('getRabbitMqConnectionService')), ($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\DomainEventJsonDeserializer'] ?? $container->load('getDomainEventJsonDeserializerService')), $container->getEnv('RABBITMQ_EXCHANGE'), $container->getEnv('RABBITMQ_MAX_RETRIES'));
    }
}
