<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoRepositoryMySqlService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\Videos\Infrastructure\Persistence\VideoRepositoryMySql' shared autowired service.
     *
     * @return \CodelyTv\Mooc\Videos\Infrastructure\Persistence\VideoRepositoryMySql
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Persistence/Doctrine/DoctrineRepository.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Videos/Domain/VideoRepository.php';
        include_once \dirname(__DIR__, 7).'/src/Mooc/Videos/Infrastructure/Persistence/VideoRepositoryMySql.php';

        return $container->privates['CodelyTv\\Mooc\\Videos\\Infrastructure\\Persistence\\VideoRepositoryMySql'] = new \CodelyTv\Mooc\Videos\Infrastructure\Persistence\VideoRepositoryMySql(($container->services['Doctrine\\ORM\\EntityManager'] ?? $container->load('getEntityManagerService')));
    }
}
