<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoFinderService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Mooc\Videos\Application\Find\VideoFinder' shared autowired service.
     *
     * @return \CodelyTv\Mooc\Videos\Application\Find\VideoFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Mooc/Videos/Application/Find/VideoFinder.php';

        return $container->privates['CodelyTv\\Mooc\\Videos\\Application\\Find\\VideoFinder'] = new \CodelyTv\Mooc\Videos\Application\Find\VideoFinder(($container->privates['CodelyTv\\Mooc\\Videos\\Infrastructure\\Persistence\\VideoRepositoryMySql'] ?? $container->load('getVideoRepositoryMySqlService')));
    }
}
