<?php

namespace ContainerESpBA67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWithPrometheusMonitoringEventBusService extends CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainer
{
    /**
     * Gets the private 'CodelyTv\Shared\Infrastructure\Bus\Event\WithMonitoring\WithPrometheusMonitoringEventBus' shared autowired service.
     *
     * @return \CodelyTv\Shared\Infrastructure\Bus\Event\WithMonitoring\WithPrometheusMonitoringEventBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 7).'/src/Shared/Domain/Bus/Event/EventBus.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Bus/Event/WithMonitoring/WithPrometheusMonitoringEventBus.php';
        include_once \dirname(__DIR__, 7).'/src/Shared/Infrastructure/Monitoring/PrometheusMonitor.php';

        return $container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\WithMonitoring\\WithPrometheusMonitoringEventBus'] = new \CodelyTv\Shared\Infrastructure\Bus\Event\WithMonitoring\WithPrometheusMonitoringEventBus(($container->privates['CodelyTv\\Shared\\Infrastructure\\Monitoring\\PrometheusMonitor'] ??= new \CodelyTv\Shared\Infrastructure\Monitoring\PrometheusMonitor()), 'mooc_backend', ($container->privates['CodelyTv\\Shared\\Infrastructure\\Bus\\Event\\RabbitMq\\RabbitMqEventBus'] ?? $container->load('getRabbitMqEventBusService')));
    }
}
